version: '3'

services:
  nginxproxy:
    depends_on:
      - nginx
      - db
      - wordpress
      - app
    image: nginx:latest
    container_name: proxyserver
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf


  nginx:
    image: nginx:latest
    container_name: frontend
    restart: always
    volumes:
      - ./front:/usr/share/nginx/html 


  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: tomcatapp
    restart: always

  db:
    image: mysql:5.7
    container_name: mysqldb
    volumes:
      - mydb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: shop
      MYSQL_USER: floweradmin
      MYSQL_PASSWORD: floweradnib


  wordpress:
    depends_on:
      - db
    build:
      context: ./wp
      dockerfile: Dockerfile
    container_name: wp
    restart: always
    volumes:
      - ./html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: floweradmin
      WORDPRESS_DB_PASSWORD: floweradmin
      WORDPRESS_DB_NAME: shop





        
volumes:
  mydb:
